# Generated by Django 4.1.7 on 2023-08-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_project_project_core_projec_created_25e517_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='describtion',
        ),
    ]
