# Generated by Django 4.1.7 on 2023-08-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_description_project_describtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='describtion',
            new_name='description',
        ),
    ]
