# Generated by Django 4.1.7 on 2023-08-29 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
