# Generated by Django 4.1.7 on 2023-08-29 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_project_core_projec_created_25e517_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='about',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
    ]
