# Generated by Django 4.1.7 on 2023-09-24 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
