# Generated by Django 4.1.7 on 2023-09-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_socialmedia_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.AddField(
            model_name='about',
            name='links',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
