# Generated by Django 4.1.7 on 2023-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_socialmedia_about_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='links',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='about',
            name='github',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
