# Generated by Django 4.1.7 on 2023-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_links_about_facebook_about_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='github',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedin',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='twitter',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
