# Generated by Django 4.1.7 on 2023-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_about_facebook_alter_about_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
